//
//  SimpleGroup.swift
//  Sveta's task by Ivan
//
//  Created by mac on 13.05.2022.
//

import Foundation


struct SimpleGroup {
    let id: UUID = UUID()
    var name: String = ""
    var photos: [SimplePhoto] = []
    var thumbnailPhoto: SimplePhoto  = SimplePhoto(name: "")
    var groupDescriptionText: String = ""
    var isSubscribedToUser: Bool = false
    var users: [SimpleUser] = []
}


var simpleGroupTestData: [SimpleGroup] = [
    SimpleGroup(name: "Cats", photos: [SimplePhoto(name: "cat2"),SimplePhoto(name: "cat3"),SimplePhoto(name: "cat4"),SimplePhoto(name: "cat5")], thumbnailPhoto: SimplePhoto(name: "cat2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Birds", photos: [SimplePhoto(name: "bird1"),SimplePhoto(name: "bird2"),SimplePhoto(name: "bird3"),SimplePhoto(name: "bird4"),SimplePhoto(name: "bird5"),SimplePhoto(name: "bird6"),SimplePhoto(name: "bird7")], thumbnailPhoto: SimplePhoto(name: "bird1"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Cars", photos: [SimplePhoto(name: "car1"),SimplePhoto(name: "car2"),SimplePhoto(name: "car3"),SimplePhoto(name: "car4"),SimplePhoto(name: "car5")], thumbnailPhoto: SimplePhoto(name: "car2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Dogs", photos: [SimplePhoto(name: "dog1"),SimplePhoto(name: "dog2"),SimplePhoto(name: "dog3"),SimplePhoto(name: "dog4"),SimplePhoto(name: "dog5"),SimplePhoto(name: "dog6"),SimplePhoto(name: "dog7")], thumbnailPhoto: SimplePhoto(name: "dog4"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Fish", photos: [SimplePhoto(name: "fish1"),SimplePhoto(name: "fish2"),SimplePhoto(name: "fish3")], thumbnailPhoto: SimplePhoto(name: "fish2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Houses", photos: [SimplePhoto(name: "house1"),SimplePhoto(name: "house2"),SimplePhoto(name: "house3")], thumbnailPhoto: SimplePhoto(name: "house2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Mountains", photos: [SimplePhoto(name: "mountain1"),SimplePhoto(name: "mountain2"),SimplePhoto(name: "mountain3")], thumbnailPhoto: SimplePhoto(name: "mountain3"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Phones", photos: [SimplePhoto(name: "phone1"),SimplePhoto(name: "phone2"),SimplePhoto(name: "phone3")], thumbnailPhoto: SimplePhoto(name: "phone2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Tables", photos: [SimplePhoto(name: "table1"),SimplePhoto(name: "table2"),SimplePhoto(name: "table3")], thumbnailPhoto: SimplePhoto(name: "table2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. "),
    
    SimpleGroup(name: "Trees", photos: [SimplePhoto(name: "tree1"),SimplePhoto(name: "tree2"),SimplePhoto(name: "tree3")], thumbnailPhoto: SimplePhoto(name: "tree2"), groupDescriptionText: "Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. Some long text, very long text. ")
]
